export type TrainingResource = {
    url: string;
    title?: string;
  };
  
  export const TRAINING_CATALOG: Record<string, TrainingResource> = {
    INTERNAL_ASSESSMENT: { url: "internal-assessment" },
    INTERNAL_DOCS: { url: "internal-docs" },
    INTERNAL_LAB: { url: "internal-lab" },
    INTERNAL_PROJECT: { url: "internal-project" },
    DOCS_ANTHROPIC_COM_EN_DOCS_BUILD_WITH_CLAUDE_STREAMING: { url: "https://docs.anthropic.com/en/docs/build-with-claude/streaming" },
    DOCS_ANTHROPIC_COM_EN_DOCS_QUICKSTART: { url: "https://docs.anthropic.com/en/docs/quickstart" },
    DOCS_LLAMAINDEX_AI_EN_STABLE: { url: "https://docs.llamaindex.ai/en/stable/" },
    DOCS_PINECONE_IO: { url: "https://docs.pinecone.io/" },
    PLATFORM_OPENAI_COM_DOCS_GUIDES_MODERATION: { url: "https://platform.openai.com/docs/guides/moderation" },
    PYTHON_LANGCHAIN_COM_DOCS_GET_STARTED_INTRODUCTION: { url: "https://python.langchain.com/docs/get_started/introduction" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_AGENTS: { url: "https://python.langchain.com/docs/modules/agents/" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_DATA_CONNECTION: { url: "https://python.langchain.com/docs/modules/data_connection/" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_MEMORY: { url: "https://python.langchain.com/docs/modules/memory/" },
    PYTHON_LANGCHAIN_COM_DOCS_USE_CASES_MULTI_AGENT: { url: "https://python.langchain.com/docs/use_cases/multi_agent/" },
    WWW_LINKEDIN_COM_LEARNING_ADVANCED_PROMPT_ENGINEERING_TECHNIQUES: { url: "https://www.linkedin.com/learning/advanced-prompt-engineering-techniques", title: "Advanced Prompt Engineering Techniques" },
    WWW_LINKEDIN_COM_LEARNING_AI_FOR_ARCHITECTS: { url: "https://www.linkedin.com/learning/ai-for-architects" },
    WWW_LINKEDIN_COM_LEARNING_AI_FUNDAMENTALS_FOR_DATA_PROFESSIONALS: { url: "https://www.linkedin.com/learning/ai-fundamentals-for-data-professionals", title: "AI Fundamentals for Data Professionals" },
    WWW_LINKEDIN_COM_LEARNING_AMAZON_WEB_SERVICES_DEPLOYING_AND_PROVISIONING: { url: "https://www.linkedin.com/learning/amazon-web-services-deploying-and-provisioning" },
    WWW_LINKEDIN_COM_LEARNING_AMAZON_WEB_SERVICES_HIGH_AVAILABILITY: { url: "https://www.linkedin.com/learning/amazon-web-services-high-availability" },
    WWW_LINKEDIN_COM_LEARNING_API_DEVELOPMENT_AND_MANAGEMENT: { url: "https://www.linkedin.com/learning/api-development-and-management" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_ETHICS_IN_PRACTICE: { url: "https://www.linkedin.com/learning/artificial-intelligence-ethics-in-practice" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_FOUNDATIONS_MACHINE_LEARNING: { url: "https://www.linkedin.com/learning/artificial-intelligence-foundations-machine-learning" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_FOUNDATIONS_THINKING_MACHINES: { url: "https://www.linkedin.com/learning/artificial-intelligence-foundations-thinking-machines" },
    WWW_LINKEDIN_COM_LEARNING_ASYNCHRONOUS_PYTHON_BOOST_PERFORMANCE_AND_EFFICIENCY_F: { url: "https://www.linkedin.com/learning/asynchronous-python-boost-performance-and-efficiency-for-real-world-apps", title: "Asynchronous Python: Boost Performance and Efficiency for Real-World Apps" },
    WWW_LINKEDIN_COM_LEARNING_AWS_COST_MANAGEMENT: { url: "https://www.linkedin.com/learning/aws-cost-management" },
    WWW_LINKEDIN_COM_LEARNING_AWS_ESSENTIAL_TRAINING_FOR_ARCHITECTS: { url: "https://www.linkedin.com/learning/aws-essential-training-for-architects" },
    WWW_LINKEDIN_COM_LEARNING_BUILDING_AI_AGENTS_WITH_LANGCHAIN: { url: "https://www.linkedin.com/learning/building-ai-agents-with-langchain" },
    WWW_LINKEDIN_COM_LEARNING_BUILDING_AI_POWERED_APPLICATIONS_WITH_LANGCHAIN: { url: "https://www.linkedin.com/learning/building-ai-powered-applications-with-langchain" },
    WWW_LINKEDIN_COM_LEARNING_BUILDING_A_BUSINESS_CASE: { url: "https://www.linkedin.com/learning/building-a-business-case" },
    WWW_LINKEDIN_COM_LEARNING_BUSINESS_ANALYSIS_FOUNDATIONS: { url: "https://www.linkedin.com/learning/business-analysis-foundations" },
    WWW_LINKEDIN_COM_LEARNING_CLOUD_ARCHITECTURE_COST_OPTIMIZATION: { url: "https://www.linkedin.com/learning/cloud-architecture-cost-optimization" },
    WWW_LINKEDIN_COM_LEARNING_COMMUNICATING_ABOUT_ARCHITECTURE: { url: "https://www.linkedin.com/learning/communicating-about-architecture" },
    WWW_LINKEDIN_COM_LEARNING_CYBERSECURITY_ARCHITECTURE_STANDARDS_AND_FRAMEWORKS: { url: "https://www.linkedin.com/learning/cybersecurity-architecture-standards-and-frameworks" },
    WWW_LINKEDIN_COM_LEARNING_DATABASE_FOUNDATIONS_INTRO_TO_DATABASES: { url: "https://www.linkedin.com/learning/database-foundations-intro-to-databases", title: "Database Foundations: Intro to Databases" },
    WWW_LINKEDIN_COM_LEARNING_DATA_PIPELINE_AUTOMATION_WITH_GITHUB_ACTIONS_USING_R_A: { url: "https://www.linkedin.com/learning/data-pipeline-automation-with-github-actions-using-r-and-python", title: "Data Pipeline Automation with GitHub Actions Using R and Python" },
    WWW_LINKEDIN_COM_LEARNING_DATA_PRIVACY_AND_SECURITY: { url: "https://www.linkedin.com/learning/data-privacy-and-security" },
    WWW_LINKEDIN_COM_LEARNING_DEVOPS_FOUNDATIONS_CONTAINERS: { url: "https://www.linkedin.com/learning/devops-foundations-containers" },
    WWW_LINKEDIN_COM_LEARNING_DEVOPS_FOUNDATIONS_CONTINUOUS_DELIVERY_CONTINUOUS_INTE: { url: "https://www.linkedin.com/learning/devops-foundations-continuous-delivery-continuous-integration" },
    WWW_LINKEDIN_COM_LEARNING_ENTERPRISE_ARCHITECTURE_FOUNDATIONS: { url: "https://www.linkedin.com/learning/enterprise-architecture-foundations" },
    WWW_LINKEDIN_COM_LEARNING_ENTERPRISE_RISK_MANAGEMENT: { url: "https://www.linkedin.com/learning/enterprise-risk-management" },
    WWW_LINKEDIN_COM_LEARNING_GENERATIVE_AI_WORKING_WITH_LARGE_LANGUAGE_MODELS: { url: "https://www.linkedin.com/learning/generative-ai-working-with-large-language-models" },
    WWW_LINKEDIN_COM_LEARNING_HANDS_ON_AI_INTRODUCTION_TO_RETRIEVAL_AUGMENTED_GENERA: { url: "https://www.linkedin.com/learning/hands-on-ai-introduction-to-retrieval-augmented-generation-rag", title: "Hands-on AI: Introduction to Retrieval-Augmented Generation (RAG)" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_LARGE_LANGUAGE_MODELS: { url: "https://www.linkedin.com/learning/introduction-to-large-language-models" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_PROMPT_ENGINEERING_FOR_GENERATIVE_AI_2: { url: "https://www.linkedin.com/learning/introduction-to-prompt-engineering-for-generative-ai-24636124", title: "Introduction to Prompt Engineering for Generative AI" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_SQLITE: { url: "https://www.linkedin.com/learning/introduction-to-sqlite", title: "Introduction to SQLite" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_APACHE_KAFKA: { url: "https://www.linkedin.com/learning/learning-apache-kafka" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_INFRASTRUCTURE_AS_CODE: { url: "https://www.linkedin.com/learning/learning-infrastructure-as-code" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_PROMETHEUS: { url: "https://www.linkedin.com/learning/learning-prometheus" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_PYTHON_25309312: { url: "https://www.linkedin.com/learning/learning-python-25309312", title: "Learning Python" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_TERRAFORM_15575129: { url: "https://www.linkedin.com/learning/learning-terraform-15575129" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_UML: { url: "https://www.linkedin.com/learning/learning-uml" },
    WWW_LINKEDIN_COM_LEARNING_MACHINE_LEARNING_OPERATIONS_MLOPS_FUNDAMENTALS: { url: "https://www.linkedin.com/learning/machine-learning-operations-mlops-fundamentals" },
    WWW_LINKEDIN_COM_LEARNING_MICROSERVICES_FOUNDATIONS: { url: "https://www.linkedin.com/learning/microservices-foundations" },
    WWW_LINKEDIN_COM_LEARNING_OPENAI_API_INTRODUCTION: { url: "https://www.linkedin.com/learning/openai-api-introduction", title: "OpenAI API: Introduction" },
    WWW_LINKEDIN_COM_LEARNING_PROGRAMMING_FOUNDATIONS_APIS_AND_WEB_SERVICES: { url: "https://www.linkedin.com/learning/programming-foundations-apis-and-web-services" },
    WWW_LINKEDIN_COM_LEARNING_PROJECT_MANAGEMENT_FOUNDATIONS_STAKEHOLDERS: { url: "https://www.linkedin.com/learning/project-management-foundations-stakeholders" },
    WWW_LINKEDIN_COM_LEARNING_PROMPT_ENGINEERING_HOW_TO_TALK_TO_THE_AIS: { url: "https://www.linkedin.com/learning/prompt-engineering-how-to-talk-to-the-ais" },
    WWW_LINKEDIN_COM_LEARNING_PROMPT_ENGINEERING_WITH_LANGCHAIN: { url: "https://www.linkedin.com/learning/prompt-engineering-with-langchain", title: "Prompt Engineering with LangChain" },
    WWW_LINKEDIN_COM_LEARNING_PYTHON_ESSENTIAL_TRAINING_18764650: { url: "https://www.linkedin.com/learning/python-essential-training-18764650" },
    WWW_LINKEDIN_COM_LEARNING_PYTHON_WORKING_WITH_REST_AND_WEB_DATA: { url: "https://www.linkedin.com/learning/python-working-with-rest-and-web-data", title: "Python: Working with REST and Web Data" },
    WWW_LINKEDIN_COM_LEARNING_SEARCH_TECHNIQUES_FOR_WEB_DEVELOPERS: { url: "https://www.linkedin.com/learning/search-techniques-for-web-developers" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_ARCHITECTURE_DOCUMENTING_ARCHITECTURE: { url: "https://www.linkedin.com/learning/software-architecture-documenting-architecture" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_ARCHITECTURE_FOUNDATIONS: { url: "https://www.linkedin.com/learning/software-architecture-foundations" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_ARCHITECTURE_PATTERNS_FOR_DEVELOPERS: { url: "https://www.linkedin.com/learning/software-architecture-patterns-for-developers" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_DESIGN_FROM_REQUIREMENTS_TO_RELEASE: { url: "https://www.linkedin.com/learning/software-design-from-requirements-to-release" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_TESTING_FOUNDATIONS_TEST_TECHNIQUES: { url: "https://www.linkedin.com/learning/software-testing-foundations-test-techniques" },
    WWW_LINKEDIN_COM_LEARNING_USER_EXPERIENCE_FOR_WEB_DESIGN: { url: "https://www.linkedin.com/learning/user-experience-for-web-design" },
    WWW_LINKEDIN_COM_LEARNING_VENDOR_MANAGEMENT_FOUNDATIONS: { url: "https://www.linkedin.com/learning/vendor-management-foundations" },
  };  