export type TrainingResource = {
    url: string;
    title?: string;
  };
  
  export const TRAINING_CATALOG: Record<string, TrainingResource> = {
    INTERNAL_ASSESSMENT: { url: "internal-assessment" },
    INTERNAL_DOCS: { url: "internal-docs" },
    INTERNAL_LAB: { url: "internal-lab" },
    INTERNAL_PROJECT: { url: "internal-project" },
    DOCS_ANTHROPIC_COM_EN_DOCS_BUILD_WITH_CLAUDE_STREAMING: { url: "https://docs.anthropic.com/en/docs/build-with-claude/streaming" },
    DOCS_ANTHROPIC_COM_EN_DOCS: { url: "https://www.linkedin.com/learning/ai-automation-with-anthropic-claude-api-s-agentic-computer-use?utm_source=chatgpt.com" },
    DOCS_LLAMAINDEX_AI_EN_STABLE: { url: "https://docs.llamaindex.ai/en/stable/" },
    DOCS_PINECONE_IO: { url: "https://docs.pinecone.io/" },
    PLATFORM_OPENAI_COM_DOCS_GUIDES_MODERATION: { url: "https://platform.openai.com/docs/guides/moderation" },
    PYTHON_LANGCHAIN_COM_DOCS_GET_STARTED_INTRODUCTION: { url: "https://python.langchain.com/docs/get_started/introduction" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_AGENTS: { url: "https://python.langchain.com/docs/modules/agents/" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_DATA_CONNECTION: { url: "https://python.langchain.com/docs/modules/data_connection/" },
    PYTHON_LANGCHAIN_COM_DOCS_MODULES_MEMORY: { url: "https://python.langchain.com/docs/modules/memory/" },
    PYTHON_LANGCHAIN_COM_DOCS_USE_CASES_MULTI_AGENT: { url: "https://python.langchain.com/docs/use_cases/multi_agent/" },
    LANGFLOW_CHUNKING_STRATEGIES: { url: "https://www.langflow.org/blog/text-splitting-beyond-basic-rag" },
    WWW_LINKEDIN_COM_LEARNING_DATA_COLLECTION_AND_LOADERS: { url: "https://docs.langchain.com/oss/python/integrations/document_loaders" },
    WWW_VECTOR_EMBEDINGS: { url: "https://platform.openai.com/docs/guides/embeddings" },
    WWW_VECTOR_DATABASES: { url: "https://platform.openai.com/docs/guides/retrieval" },
    WWW_LINKEDIN_COM_LEARNING_ADVANCED_PROMPT_ENGINEERING_TECHNIQUES: { url: "https://www.linkedin.com/learning/advanced-prompt-engineering-techniques"},
    WWW_LINKEDIN_COM_LEARNING_MLOPS_ESSENTIALS: { url: "https://www.linkedin.com/learning/mlops-essentials-model-development-and-integration/getting-started-with-mlops?u=2202746"},
    WWW_LINKEDIN_COM_LEARNING_FEW_SHOT_TECHNIQUES: { url: "https://www.linkedin.com/learning/advanced-prompt-engineering-techniques/zero-shot-and-few-shot-prompting" },
    WWW_LINKEDIN_COM_LEARNING_FUNCTION_CALLING: { url: "https://www.linkedin.com/learning/gemini-api-tool-and-function-calling/function-calling-with-the-gemini-api?resume=false&u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_AI_ARCHITECTURE_FOUNDATIONS: { url: "https://www.linkedin.com/learning/agentic-ai-architecture-foundations-designing-autonomous-ai-systems/introduction?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_AI_FUNDAMENTALS_FOR_DATA_PROFESSIONALS: { url: "https://www.linkedin.com/learning/ai-fundamentals-for-data-professionals" },
    WWW_LINKEDIN_COM_LEARNING_AMAZON_WEB_SERVICES_CLOUDFORMATION: { url: "https://www.linkedin.com/learning/introduction-to-aws-cloudformation/introduction?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_AMAZON_WEB_SERVICES_HIGH_AVAILABILITY: { url: "https://www.linkedin.com/learning/amazon-web-services-high-availability" },
    WWW_LINKEDIN_COM_LEARNING_API_DEVELOPMENT: { url: "https://www.linkedin.com/learning/data-integration-and-api-development-for-ai-applications/the-need-for-data-integration-and-apis?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_STREAMING_RESPONSES: { url: "https://platform.openai.com/docs/guides/streaming-responses" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_ETHICS: { url: "https://www.linkedin.com/learning/artificial-general-intelligence-the-technology-impact-and-ethics/inventing-tomorrow-agi-and-what-it-means-for-humanity?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_FOUNDATIONS_MACHINE_LEARNING: { url: "https://www.linkedin.com/learning/artificial-intelligence-foundations-machine-learning" },
    WWW_LINKEDIN_COM_LEARNING_ARTIFICIAL_INTELLIGENCE_FOUNDATIONS_THINKING_MACHINES: { url: "https://www.linkedin.com/learning/artificial-intelligence-foundations-thinking-machines" },
    WWW_LINKEDIN_COM_LEARNING_ASYNCHRONOUS_PYTHON_BOOST_PERFORMANCE_AND_EFFICIENCY_F: { url: "https://www.linkedin.com/learning/asynchronous-python-boost-performance-and-efficiency-for-real-world-apps" },
    WWW_LINKEDIN_COM_LEARNING_AWS_COST_OPTIMIZATION: { url: "https://www.linkedin.com/learning/applying-cost-optimization-tools-to-your-aws-workloads/aws-cost-management-tools?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_AWS_ESSENTIAL_TRAINING_FOR_ARCHITECTS: { url: "https://www.linkedin.com/learning/aws-essential-training-for-architects" },
    WWW_LINKEDIN_COM_LEARNING_AGENTS_ARCHITECTURE_LANGCHAIN: { url: "https://docs.langchain.com/oss/python/langchain/overview" },
    WWW_LINKEDIN_COM_LEARNING_LANGCHAIN_SEQUENCES: { url: "https://www.linkedin.com/learning/prompt-engineering-with-langchain/chains-construct-sequences-of-calls?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_BUILDING_A_BUSINESS_CASE: { url: "https://www.linkedin.com/learning/writing-a-business-case/what-a-business-case-can-do-for-you?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_BUSINESS_ANALYSIS_FOUNDATIONS: { url: "https://www.linkedin.com/learning/business-analysis-foundations-4/prevent-project-failure-with-business-analysis?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_CLOUD_ARCHITECTURE_COST_OPTIMIZATION: { url: "https://www.linkedin.com/learning/applying-cost-optimization-tools-to-your-aws-workloads/cost-optimization-pillar-aws-well-architected-framework?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_COMMUNICATING_ABOUT_ARCHITECTURE: { url: "https://www.linkedin.com/learning/agentic-ai-solution-communication-architectures/introduction?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_CYBERSECURITY_ARCHITECTURE: { url: "https://www.linkedin.com/learning/cybersecurity-foundations-security-architecture/protect-your-enterprise-with-the-four-disciplines-of-cybersecurity?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_DATABASE_FOUNDATIONS_INTRO_TO_DATABASES: { url: "https://www.linkedin.com/learning/introduction-to-ai-native-vector-databases/learning-ai-native-vector-databases?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_EMBEDDINGS: { url: "https://www.linkedin.com/learning/openai-api-embeddings/introduction-to-embeddings?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_DATA_PIPELINE_AUTOMATION_WITH_GITHUB_ACTIONS_USING_R_A: { url: "https://www.linkedin.com/learning/data-pipeline-automation-with-github-actions-using-r-and-python" },
    WWW_LINKEDIN_COM_LEARNING_DATA_PRIVACY_AND_SECURITY: { url: "https://www.linkedin.com/learning/navigating-ai-regulations-a-business-guide-to-risk-responsibility-and-strategy/what-business-leaders-need-to-know-about-ai-regulations?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_DEVOPS_FOUNDATIONS_CONTAINERS: { url: "https://www.linkedin.com/learning/devops-foundations-containers" },
    WWW_LINKEDIN_COM_LEARNING_DEVOPS_FOUNDATIONS_CONTINUOUS_DELIVERY_CONTINUOUS_INTE: { url: "https://www.linkedin.com/learning/devops-foundations-continuous-delivery-continuous-integration" },
    WWW_LINKEDIN_COM_LEARNING_ENTERPRISE_ARCHITECTURE_FOUNDATIONS: { url: "https://www.linkedin.com/learning/enterprise-architecture-foundations" },
    WWW_LINKEDIN_COM_LEARNING_ENTERPRISE_RISK_MANAGEMENT: { url: "linkedin.com/learning/enterprise-security-risk-management-for-cybersecurity-managers-from-assessment-to-governance-with-iso-iec-2700/why-enterprise-risk-management-erm-matters-for-security-leaders?u=2202746" },
    WWW_LINKEDIN_COM_STATE_MANAGEMENT: { url: "https://www.linkedin.com/posts/bijit-ghosh-48281a78_ai-agents-state-management-state-graph-activity-7345252834507980802-LqXp" },
    WWW_LINKEDIN_COM_LEARNING_GENERATIVE_AI_WORKING_WITH_LARGE_LANGUAGE_MODELS: { url: "https://www.linkedin.com/learning/generative-ai-working-with-large-language-models" },
    WWW_LINKEDIN_COM_LEARNING_HANDS_ON_AI_INTRODUCTION_TO_RETRIEVAL_AUGMENTED_GENERA: { url: "https://www.linkedin.com/learning/hands-on-ai-introduction-to-retrieval-augmented-generation-rag" },
    LONGHAIN_ADVANCED_RETRIEVAL_ESTRATEGY: { url: "https://docs.langchain.com/oss/python/langchain/rag" },
    LONGHAIN_AGENTIC_WORKFLOW_DESIGN: { url: "https://docs.langchain.com/oss/python/langgraph/workflows-agents" },
    LONGHAIN_OBSERVABILITY: { url: "https://docs.langchain.com/langsmith/observability" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_LARGE_LANGUAGE_MODELS: { url: "https://www.linkedin.com/learning/introduction-to-large-language-models" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_PROMPT_ENGINEERING_FOR_GENERATIVE_AI_2: { url: "https://www.linkedin.com/learning/introduction-to-prompt-engineering-for-generative-ai-24636124" },
    WWW_LINKEDIN_COM_LEARNING_INTRODUCTION_TO_SQLITE: { url: "https://www.linkedin.com/learning/introduction-to-sqlite" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_APACHE_KAFKA: { url: "https://www.linkedin.com/learning/apache-kafka-essential-training-getting-started-22398044/getting-started-with-apache-kafka?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_INFRASTRUCTURE_AS_CODE: { url: "https://www.linkedin.com/learning/devops-foundations-infrastructure-as-code-18965758/make-your-systems-better-with-infrastructure-as-code?u=2202746" },
    WWW_LEARNING_PROMETHEUS: { url: "https://prometheus.io/docs/tutorials/getting_started/" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_PYTHON_25309312: { url: "https://www.linkedin.com/learning/learning-python-25309312" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_TERRAFORM_15575129: { url: "https://www.linkedin.com/learning/learning-terraform-15575129" },
    WWW_LINKEDIN_COM_LEARNING_LEARNING_UML: { url: "https://www.linkedin.com/learning/software-design-modeling-with-uml/a-picture-is-worth-a-thousand-words?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_CI_CD: { url: "https://www.linkedin.com/learning/microsoft-azure-machine-learning-fundamentals/ci-cd-with-machine-learning?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_MICROSERVICES_FOUNDATIONS: { url: "https://www.linkedin.com/learning/microservices-foundations" },
    WWW_LINKEDIN_COM_LEARNING_OPENAI_API_INTRODUCTION: { url: "https://www.linkedin.com/learning/openai-api-introduction" },
    WWW_LINKEDIN_COM_LEARNING_PROGRAMMING_FOUNDATIONS_APIS_AND_WEB_SERVICES: { url: "https://www.linkedin.com/learning/programming-foundations-apis-and-web-services" },
    WWW_LINKEDIN_COM_LEARNING_PROJECT_MANAGEMENT_PROJECT_STAKEHOLDERS: { url: "https://www.linkedin.com/learning/managing-project-stakeholders-2/stakeholders-drive-project-success-23499179?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_PROMPT_ENGINEERING_HOW_TO_TALK_TO_THE_AIS: { url: "https://www.linkedin.com/learning/prompt-engineering-how-to-talk-to-the-ais" },
    WWW_LINKEDIN_COM_LEARNING_PROMPT_ENGINEERING_WITH_LANGCHAIN: { url: "https://www.linkedin.com/learning/prompt-engineering-with-langchain" },
    WWW_LINKEDIN_COM_LEARNING_PYTHON_ESSENTIAL_TRAINING_18764650: { url: "https://www.linkedin.com/learning/python-essential-training-18764650" },
    WWW_LINKEDIN_COM_LEARNING_PYTHON_WORKING_WITH_REST_AND_WEB_DATA: { url: "https://www.linkedin.com/learning/python-working-with-rest-and-web-data" },
    WWW_LINKEDIN_COM_LEARNING_SEARCH_TECHNIQUES_FOR_WEB_DEVELOPERS: { url: "https://www.linkedin.com/learning/search-techniques-for-web-developers" },
    WWW_LINKEDIN_COM_LEARNING_TECHNICAL_DOCUMENTING_GITHUB: { url: "https://www.linkedin.com/learning/creating-technical-documentation-with-github/getting-with-technical-documentation-in-github?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_ARCHITECTURE_FOUNDATIONS: { url: "https://www.linkedin.com/learning/software-architecture-foundations" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_ARCHITECTURE_PATTERNS_FOR_DEVELOPERS: { url: "https://www.linkedin.com/learning/software-architecture-patterns-for-developers" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_DESIGN_FROM_REQUIREMENTS_TO_RELEASE: { url: "https://www.linkedin.com/learning/software-design-from-requirements-to-release" },
    WWW_LINKEDIN_COM_LEARNING_SOFTWARE_TESTING_FOUNDATIONS_TEST_TECHNIQUES: { url: "https://www.linkedin.com/learning/software-testing-foundations-test-techniques" },
    WWW_LINKEDIN_COM_LEARNING_USER_EXPERIENCE_FOR_WEB_DESIGN: { url: "https://www.linkedin.com/learning/user-experience-for-web-design" },
    WWW_LINKEDIN_COM_LEARNING_VENDOR_MANAGEMENT_FOUNDATIONS: { url: "https://www.linkedin.com/learning/it-vendor-management-foundations/stand-apart-with-it-vendor-management-know-how?u=2202746" },
    WWW_LINKEDIN_COM_LEARNING_MODELING_AND_MODEL_EVALUATION_METRICS: { url: "https://www.linkedin.com/learning/level-up-python-data-modeling-and-model-evaluation-metrics/python-data-modeling?u=2202746" },
  };  


  